
module .exports = {
    File: require('./src/objects/File').default,
    SmartComponent :require('./src/views/SmartComponent').default,
    SmartImageView :require('./src/cachers/imagecachers/SmartImageView').default,
    PlatformsUtils :require('./src/utils/PlatformsUtils').default,
    DateUtils :require('./src/utils/DateUtils').default,
    Storage :require('./src/utils/Storage').default,
    ToastMaster :require('./src/utils/ToastMaster').default,
    ViewUtils :require('./src/utils/ViewUtils').default,
    MediaPickerUtils :require('./src/utils/MediaPickerUtils').default,
    FileUtils :require('./src/utils/FileUtils').default,
    NetUtils :require('./src/utils/NetUtils').default,
    PhoneUtils :require('./src/utils/PhoneUtils').default,
    PersianCalendarService :require('./src/utils/PersianCalendarService').default,
    EmailUtils :require('./src/utils/EmailUtils').default,
    LangUtils :require('./src/utils/LangUtils').default,
    PermissionsManager :require('./src/permissions/PermissionsManager').default,
    CallCreator :require('./src/network/CallCreator').default,
    FileDownloader :require('./src/network/FileDownloader').default,
    AxiosInterceptorAdapter :require('./src/network/AxiosInterceptorAdapter'),
    DialogManager :require('./src/dialog/DialogManager').default,
    DialogFragment :require('./src/dialog/DialogFragment').default,
    NonBlockingView :require('./src/views/NonBlockingView').default,
    KeyboardAvoidingViewWrapper:require('./src/views/wrappers/KeyboardAvoidingViewWrapper').default,
    FadeAnimation:require('./src/dialog/DialogFragment').FadeAnimation,
    SlideAnimation:require('./src/dialog/DialogFragment').SlideAnimation,
    ScaleAnimation:require('./src/dialog/DialogFragment').ScaleAnimation,
    DialogProperties:require('./src/dialog/DialogFragment').DialogProperties,
    Gson: require('./src/objects/Gson').default
}

