
module .exports = {
    File: require('./src/objects/File'),
    SmartComponent :require('./src/views/SmartComponent'),
    SmartImageView :require('./src/cachers/imagecachers/SmartImageView'),
    PlatformsUtils :require('./src/utils/PlatformsUtils'),
    DateUtils :require('./src/utils/DateUtils'),
    Storage :require('./src/utils/Storage'),
    ToastMaster :require('./src/utils/ToastMaster'),
    UUIDUtils :require('./src/utils/UUIDUtils'),
    ViewUtils :require('./src/utils/ViewUtils'),
    MediaPickerUtils :require('./src/utils/MediaPickerUtils'),
    FileUtils :require('./src/utils/FileUtils'),
    NetUtils :require('./src/utils/NetUtils'),
    PhoneUtils :require('./src/utils/PhoneUtils'),
    PersianCalendarService :require('./src/utils/PersianCalendarService'),
    EmailUtils :require('./src/utils/EmailUtils'),
    LangUtils :require('./src/utils/LangUtils'),
    PermissionsManager :require('./src/permissions/PermissionsManager'),
    CallCreator :require('./src/network/CallCreator'),
    FileDownloader :require('./src/network/FileDownloader'),
    AxiosInterceptorAdapter :require('./src/network/AxiosInterceptorAdapter'),
    DialogManager :require('./src/dialog/DialogManager'),
    DialogFragment :require('./src/dialog/DialogFragment'),
    NonBlockingView :require('./src/views/NonBlockingView'),
    FadeAnimation:require('./src/dialog/DialogFragment').FadeAnimation,
    SlideAnimation:require('./src/dialog/DialogFragment').SlideAnimation,
    ScaleAnimation:require('./src/dialog/DialogFragment').ScaleAnimation,
    DialogProperties:require('./src/dialog/DialogFragment').DialogProperties,
}

